version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000" # Web界面访问
      - "8000:8000" # Edge Agent通信（可选）
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # 绑定宿主机的Docker Socket
      - portainer_data:/data # 数据存储
    networks:
      - traefik_net
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager # 在Swarm模式下仅运行在管理节点（可选）

volumes:
  portainer_data:
    driver: local

networks:
  traefik_net:
    external: true 