version: "3"

services:
  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./data:/var/lib/grafana
    networks:
      - grafana-net

networks:
  grafana-net:
    driver: bridge
