api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"
  metrics:
    address: ":8082"

certificatesResolvers:
  autossl:
    acme:
      email: your-email@example.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
    

providers:
  file:
    directory: /etc/traefik/vhost
    watch: true
  consulCatalog:
    endpoint:
      address: "consul:8500"
      token: "a505326722"
    exposedByDefault: true
    refreshInterval: "5s"
    connectAware: true
    connectByDefault: false
  consul:
    endpoints:
      - "consul:8500"
    token: "a505326722"
    rootKey: "traefik"
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
      
log:
  level: "DEBUG"
  format: "json"
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: "json"
  bufferingSize: 100
  fields:
    headers:
      defaultMode: drop
      names:
        Authorization: keep
        User-Agent: keep
        Origin: keep

metrics:
  prometheus:
    entryPoint: metrics