/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb']
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    AResult: typeof import('@arco-design/web-vue')['Result']
    Aside: typeof import('./src/components/frame/aside.vue')['default']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ATable: typeof import('@arco-design/web-vue')['Table']
    Breadcrumb: typeof import('./src/components/frame/header/breadcrumb.vue')['default']
    Footer: typeof import('./src/components/frame/footer.vue')['default']
    Frame: typeof import('./src/components/frame/frame.vue')['default']
    Header: typeof import('./src/components/frame/header/header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User: typeof import('./src/components/frame/header/user.vue')['default']
    Wapper: typeof import('./src/components/frame/wapper.vue')['default']
  }
}
