version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    command: mongod --auth --replSet rs0
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge
